### ISSUE TITLE
Router method changes

### ISSUE THREAD

**Issue by jberger** [polettix/WebService-Fake#5]
Hello, a CPAN search noticed that you use at least one of the routing methods removed in Mojolicious 9.0, these include route, via, detour, and over. The fixes are all easy to do and are listed on the Upgrading wiki https://github.com/mojolicious/mojo/wiki/Upgrading

Thanks

**Comment by eserte** [comment]
The test suite fails now, probably because of these changes:
```
Can't locate object method "route" via package "Mojolicious::Routes" at /home/cpansand/.cpan/build/2021030711/WebService-Fake-0.004-2/blib/lib/WebService/Fake.pm line 58.
t/01-example.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```

**Comment by polettix** [comment]
Thanks both. Unfortunately I missed the first message from @jberger and triggered the error reported by @eserte - the new version is in TRIAL mode and will be for a few days.

Thanks both for the outstanding work that you do for the community, I appreciate it a lot and I'm sure everybody else does.

**Comment by polettix** [comment]
Also pushed up the minimum perl version to 5.16, Travis-CI now seems happy so let's see what CPANTESTERS have to say...

**Comment by polettix** [comment]
CPAN Testers seem happy again with the trial release, I'm doing the proper release right now. Thanks!
